export const weddingInfo = {
  bride: {
    shortName: "Việt Hoài",
    name: "Ngô Việt Hoài",
    dob: "1995-05-20",
    phone: "0912345678",
    qrCodeUrl: "CO-DAU-QR-Code.jpg",
    address: "123 Đường ABC, Quận 1, TP.HCM",
    mapUrl:
      "https://www.google.com/maps/@21.0266468,105.7703291,14z?entry=ttu&g_ep=EgoyMDI1MTAxNC4wIKXMDSoASAFQAw%3D%3D",
    father: "Ngô Xuân Nghĩa",
    mother: "Trần Hồng Thắm",
    bio: "Cô gái đến từ Xứ Huế mộng mơ, hiện đang sinh sống và làm việc tại Sài Gòn. Sau khi tốt nghiệp Học viện Báo chí và Tuyên truyền, quyết tâm theo đuổi đam mê làm phóng viên du lịch. Là người hay cười nhưng lại sống nội tâm, thích đọc sách, trồng cây và yêu thiên nhiên. Ngoài ra còn rất thích về với vôi, nuôi mèo và nuôi ước mơ cho cô một vườn trong khỏe sắc.",
    note: "Cô dâu xin chân thành cảm ơn!",
    title: "Nhà gái",
    bank: "Ngân hàng TMCP Ngoại thương Việt Nam (Vietcombank)",
    account: "001100xxxxxxx",
  },
  groom: {
    shortName: "Kiến Văn",
    name: "Hoàng Kiến Văn",
    dob: "1994-11-15",
    phone: "0987654321",
    qrCodeUrl: "CHU-RE-QR-Code.jpg",
    address: "456 Đường XYZ, Quận 3, TP.HCM",
    mapUrl:
      "https://www.google.com/maps/@21.0266468,105.7703291,14z?entry=ttu&g_ep=EgoyMDI1MTAxNC4wIKXMDSoASAFQAw%3D%3D",
    father: "Hoàng Anh Kiệt",
    mother: "Nguyễn Thị Hoài",
    bio: 'Là bác sĩ nha khoa hiện đang công tác tại một phòng khám nha khoa ở Quận 1 thành phố Hồ Chí Minh. Là một người hiền lành và ít nói. Luôn coi trọng tình cảm và yêu thương gia đình. Với anh: "Gia đình là điểm tựa vững chắc nhất và là bến đỗ bình yên không đâu sánh bằng đối với mỗi con người. Đôi luông là nơi tràn ngập sinh yêu thương để ta trở về."',
    note: "Chú rể xin chân thành cảm ơn!",
    title: "Nhà Trai",
    bank: "Ngân hàng TMCP Ngoại thương Việt Nam (Vietcombank)",
    account: "001100xxxxxxx",
  },
  weddingDate: "2025-12-20",
  weddingTime: "10:00",
}
